version: '3.3'

services:
  home-nexus-account-service:
    image: home-nexus-account-service
    container_name: home-nexus-account-service
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    networks:
      - home-nexus
      - home-nexus-databases

networks:
  home-nexus:
    external: true
  home-nexus-databases:
    external: true